services:
  - type: web
    name: incluscores-backend
    env: python
    plan: free
    runtime: python-3.11
    root: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --workers 4 --bind 0.0.0.0:$PORT --timeout 120"
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false